name: littlebrazil
description: Little Brazil Churrasco Grill
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #BLOC
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5

  #Firebase
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.6
  firebase_messaging: ^14.7.17
  firebase_analytics: ^10.8.7

  rxdart: ^0.27.7
  intl: ^0.19.0
  url_launcher: ^6.2.5
  new_version_plus: ^0.0.11
  rate_my_app: ^2.0.0
  uuid: ^4.3.2
  http: ^1.2.0
  flutter_local_notifications: ^17.0.0
  collection: ^1.18.0
  shared_preferences: ^2.2.3
  teledart: ^0.6.1

  #Internet connection
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1

  #Map SDK
  yandex_mapkit: ^4.0.1
  yandex_geocoder: ^2.3.0+1
  geolocator: ^11.0.0
  
  #Security
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0

  #UI plugins
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  page_transition: ^2.1.0
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  sliding_up_panel: ^2.0.0+1
  pin_code_fields: ^8.0.1
  mask_text_input_formatter: ^2.9.0
  qr_code_scanner: ^1.0.1
  video_player: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  #Generating splash and app icon
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#04572D"
  image: "assets/decorations/splash_icon.png"

flutter_icons:
  image_path: "assets/decorations/app_icon.png"
  android: true 
  ios: true 

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/logo/
    - assets/decorations/
    - assets/icons/
    - .env

  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Book.ttf
        - asset: assets/fonts/Gotham-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gotham-Bold.ttf
          weight: 700
    - family: Opinion
      fonts:
        - asset: assets/fonts/Opinion-Pro-Medium.otf
        - asset: assets/fonts/Opinion-Pro-SemiBold.otf
          weight: 500
        - asset: assets/fonts/Opinion-Pro-Bold.otf
          weight: 700